name: kingdom_need_you
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.0.15
  intl: ^0.20.2
  provider: ^6.1.2
  url_launcher: ^6.2.6 # ADDED FOR OPENING LINKS

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/shop/homemunyuk.png
    - assets/images/shop/away_v2.png
    - assets/images/shop/third_v2.png
    - assets/images/shop/scarf_v2.png
    - assets/images/shop/ball_v2.png
    - assets/images/shop/training_v2.png
    - assets/images/shop/flag_v2.png
    - assets/images/shop/gk_v2.png
    - assets/images/shop/gazelle_v2.png
    - assets/images/shop/gloves.png
    - assets/images/shop/logomu.png
